apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  labels:
    app: prometheus
data:
  alert-rules.yml: |
    groups:
      - name: example-rules
        rules:
          - alert: HighCPUUsage
            expr: 100 - (avg by (instance)(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
            for: 10s
            labels:
              severity: warning
            annotations:
              summary: "Hohe CPU Last auf {{ $labels.instance }}"
              description: "CPU-Auslastung liegt über 80% (aktuell: {{ $value }}%)"
